import './globals.css'
import type { Metadata } from 'next'
import '@rainbow-me/rainbowkit/styles.css';
import { Providers } from './providers';
import { ConnectButton } from '@rainbow-me/rainbowkit';
import { useWalletClient } from 'wagmi'
export const metadata: Metadata = {
  title: 'Thai Citizens',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 
{
  return (
    <html lang="en">
      <body><Providers>
      <header className="flex justify-between items-center bg-gray-800 text-white p-4">
        <div className="text-lg font-semibold">Thai Citizen ID Card</div>
        <div className="text-lg">
          <ConnectButton></ConnectButton>
        </div>
      </header>
      {children}</Providers>
      </body>
    </html>
  )
}
